---
- hosts: all
  become: yes
  vars:
  tasks:
  - name: updating the packages
    apt:
      update_cache: yes
  - name: installing java
    apt:
      name: default-jdk
      state: present
  - name: create a tomcat user
    group:
      name: ansible
      state: present
  - name: creating user with home direcotyr
    user:
      name: tomcat
      shell: /bin/bash
      group: tomcat
      home: /opt/tomcat
      move_home: yes
  - name: installing unzip
    apt:
      name: unzip
      state: present
  - name: downloaing and unarchive
    unarchive:
      src: http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.34/bin/apache-tomcat-8.5.34.zip
      dest: /opt/tomcat
      remote_src: yes
  - name: giving permissions for tomat user over /opt/tomcat directory
    command: chgrp -R tomcat /opt/tomcat/apache-tomcat-8.5.34
  - name: giving user permissions
    command: chown -R tomcat /opt/tomcat/apache-tomcat-8.5.34
  - name: changing mode of the tomcat home directory
    command: chmod -R 755 /opt/tomcat
  - name: create a systemd service file
    template:
      src: templates/tomcat.service.j2
      dest: /etc/systemd/system/tomcat.service
      mode: '0777'
  - name: runnig deamon reload command
    systemd:
      state: started
      daemon_reload: yes
      name: tomcat
  - name: Configure Tomcat Web Management Console
    template:
      src: templates/tomcat-users.xml.j2
      dest: /opt/tomcat/apache-tomcat-8.5.34/conf/tomcat-users.xml

  

    

