---
- hosts: tom
  become: yes
  tasks:
  - name: installing java
    apt:
      name: openjdk-8-jdk
      state: present
  - name: update the packages
    apt:
      update_cache: yes
  - name: creatind directory for tocmat
    file:
      path: /opt/tomcat
      state: directory
      mode: 0755
  - name: isntall unzip soft
    apt:
      name: unzip
      state: present
  - name: copy and extract the tomcat zip file
    unarchive:
      src: apache-tomcat-8.5.33.zip
      dest: /opt/tomcat
  - name: change script permisions
    command: chmod 777 /opt/tomcat/apache-tomcat-8.5.33/bin/startup.sh
  - name: create symbolic link for statup scrilpt
    command: ln -s /opt/tomcat/apache-tomcat-8.5.33/bin/startup.sh /usr/bin/tomcatup
    when: $(! -s /etc/sample.txt)
  - name: create symbolic link for shutdown scrpt
    command: ln -s /opt/tomcat/apache-tomcat-8.5.33/bin/shutdown.sh /usr/bin/tomcatdown
    when: $(! -s /etc/sample.txt)
  - name: to run the tomcat as root from anywherer in the shell
    command: tomcatup
  - name: creating a file
    file:
      path: /etc/sample.txt
      state: touch
# we can run run_once also
 
  